[env:t-display]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit AMG88xx Library
    adafruit/Adafruit Unified Sensor
    bodmer/TFT_eSPI
    bblanchon/ArduinoJson
